<?php
/**
 * AutomatchUrlTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Price2Spy API
 *
 * Price2Spy REST API Documentation
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AutomatchUrlTypeTest Class Doc Comment
 *
 * @category    Class
 * @description AutomatchUrlType
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AutomatchUrlTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AutomatchUrlType"
     */
    public function testAutomatchUrlType()
    {
    }

    /**
     * Test attribute "added_by_id"
     */
    public function testPropertyAddedById()
    {
    }

    /**
     * Test attribute "approved"
     */
    public function testPropertyApproved()
    {
    }

    /**
     * Test attribute "automatch_url_fields"
     */
    public function testPropertyAutomatchUrlFields()
    {
    }

    /**
     * Test attribute "automatch_url_id"
     */
    public function testPropertyAutomatchUrlId()
    {
    }

    /**
     * Test attribute "date_added"
     */
    public function testPropertyDateAdded()
    {
    }

    /**
     * Test attribute "date_approved"
     */
    public function testPropertyDateApproved()
    {
    }

    /**
     * Test attribute "date_checked"
     */
    public function testPropertyDateChecked()
    {
    }

    /**
     * Test attribute "date_modified"
     */
    public function testPropertyDateModified()
    {
    }

    /**
     * Test attribute "match_accuracy"
     */
    public function testPropertyMatchAccuracy()
    {
    }

    /**
     * Test attribute "modified_by_id"
     */
    public function testPropertyModifiedById()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }
}
