<?php
/**
 * MatchingSuggestionsTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Price2Spy API
 *
 * Price2Spy REST API Documentation
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MatchingSuggestionsTypeTest Class Doc Comment
 *
 * @category    Class
 * @description MatchingSuggestionsType
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MatchingSuggestionsTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MatchingSuggestionsType"
     */
    public function testMatchingSuggestionsType()
    {
    }

    /**
     * Test attribute "matching_suggestion_id"
     */
    public function testPropertyMatchingSuggestionId()
    {
    }

    /**
     * Test attribute "my_product_id"
     */
    public function testPropertyMyProductId()
    {
    }

    /**
     * Test attribute "my_product_name"
     */
    public function testPropertyMyProductName()
    {
    }

    /**
     * Test attribute "suggested_url"
     */
    public function testPropertySuggestedUrl()
    {
    }

    /**
     * Test attribute "suggested_url_availability"
     */
    public function testPropertySuggestedUrlAvailability()
    {
    }

    /**
     * Test attribute "suggested_url_name"
     */
    public function testPropertySuggestedUrlName()
    {
    }

    /**
     * Test attribute "suggested_url_price"
     */
    public function testPropertySuggestedUrlPrice()
    {
    }

    /**
     * Test attribute "suggested_url_sitename"
     */
    public function testPropertySuggestedUrlSitename()
    {
    }
}
