<?php
/**
 * PriceBucketTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Price2Spy API
 *
 * Price2Spy REST API Documentation
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PriceBucketTypeTest Class Doc Comment
 *
 * @category    Class
 * @description PriceBucketType
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PriceBucketTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PriceBucketType"
     */
    public function testPriceBucketType()
    {
    }

    /**
     * Test attribute "added_by_id"
     */
    public function testPropertyAddedById()
    {
    }

    /**
     * Test attribute "date_added"
     */
    public function testPropertyDateAdded()
    {
    }

    /**
     * Test attribute "date_modified"
     */
    public function testPropertyDateModified()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "modified_by_id"
     */
    public function testPropertyModifiedById()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "price_from"
     */
    public function testPropertyPriceFrom()
    {
    }

    /**
     * Test attribute "price_to"
     */
    public function testPropertyPriceTo()
    {
    }
}
