<?php
/**
 * ProductWithUrlsTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Price2Spy API
 *
 * Price2Spy REST API Documentation
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ProductWithUrlsTypeTest Class Doc Comment
 *
 * @category    Class
 * @description ProductWithUrlsType
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductWithUrlsTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProductWithUrlsType"
     */
    public function testProductWithUrlsType()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "added_by_id"
     */
    public function testPropertyAddedById()
    {
    }

    /**
     * Test attribute "brand_id"
     */
    public function testPropertyBrandId()
    {
    }

    /**
     * Test attribute "brand_name"
     */
    public function testPropertyBrandName()
    {
    }

    /**
     * Test attribute "category_id"
     */
    public function testPropertyCategoryId()
    {
    }

    /**
     * Test attribute "category_name"
     */
    public function testPropertyCategoryName()
    {
    }

    /**
     * Test attribute "check_frequency_interval"
     */
    public function testPropertyCheckFrequencyInterval()
    {
    }

    /**
     * Test attribute "check_frequency_type"
     */
    public function testPropertyCheckFrequencyType()
    {
    }

    /**
     * Test attribute "comment1"
     */
    public function testPropertyComment1()
    {
    }

    /**
     * Test attribute "comment2"
     */
    public function testPropertyComment2()
    {
    }

    /**
     * Test attribute "custom_field1"
     */
    public function testPropertyCustomField1()
    {
    }

    /**
     * Test attribute "custom_field10"
     */
    public function testPropertyCustomField10()
    {
    }

    /**
     * Test attribute "custom_field2"
     */
    public function testPropertyCustomField2()
    {
    }

    /**
     * Test attribute "custom_field3"
     */
    public function testPropertyCustomField3()
    {
    }

    /**
     * Test attribute "custom_field4"
     */
    public function testPropertyCustomField4()
    {
    }

    /**
     * Test attribute "custom_field5"
     */
    public function testPropertyCustomField5()
    {
    }

    /**
     * Test attribute "custom_field6"
     */
    public function testPropertyCustomField6()
    {
    }

    /**
     * Test attribute "custom_field7"
     */
    public function testPropertyCustomField7()
    {
    }

    /**
     * Test attribute "custom_field8"
     */
    public function testPropertyCustomField8()
    {
    }

    /**
     * Test attribute "custom_field9"
     */
    public function testPropertyCustomField9()
    {
    }

    /**
     * Test attribute "date_added"
     */
    public function testPropertyDateAdded()
    {
    }

    /**
     * Test attribute "date_modified"
     */
    public function testPropertyDateModified()
    {
    }

    /**
     * Test attribute "internal_id"
     */
    public function testPropertyInternalId()
    {
    }

    /**
     * Test attribute "last_change"
     */
    public function testPropertyLastChange()
    {
    }

    /**
     * Test attribute "last_checked"
     */
    public function testPropertyLastChecked()
    {
    }

    /**
     * Test attribute "max_price"
     */
    public function testPropertyMaxPrice()
    {
    }

    /**
     * Test attribute "metadata1_id"
     */
    public function testPropertyMetadata1Id()
    {
    }

    /**
     * Test attribute "metadata1_name"
     */
    public function testPropertyMetadata1Name()
    {
    }

    /**
     * Test attribute "metadata2_id"
     */
    public function testPropertyMetadata2Id()
    {
    }

    /**
     * Test attribute "metadata2_name"
     */
    public function testPropertyMetadata2Name()
    {
    }

    /**
     * Test attribute "metadata3_id"
     */
    public function testPropertyMetadata3Id()
    {
    }

    /**
     * Test attribute "metadata3_name"
     */
    public function testPropertyMetadata3Name()
    {
    }

    /**
     * Test attribute "min_price"
     */
    public function testPropertyMinPrice()
    {
    }

    /**
     * Test attribute "modified_by_id"
     */
    public function testPropertyModifiedById()
    {
    }

    /**
     * Test attribute "next_checked"
     */
    public function testPropertyNextChecked()
    {
    }

    /**
     * Test attribute "product_id"
     */
    public function testPropertyProductId()
    {
    }

    /**
     * Test attribute "product_name"
     */
    public function testPropertyProductName()
    {
    }

    /**
     * Test attribute "purchase_price"
     */
    public function testPropertyPurchasePrice()
    {
    }

    /**
     * Test attribute "show_in_reports"
     */
    public function testPropertyShowInReports()
    {
    }

    /**
     * Test attribute "sku"
     */
    public function testPropertySku()
    {
    }

    /**
     * Test attribute "supplier_id"
     */
    public function testPropertySupplierId()
    {
    }

    /**
     * Test attribute "supplier_name"
     */
    public function testPropertySupplierName()
    {
    }

    /**
     * Test attribute "target_price"
     */
    public function testPropertyTargetPrice()
    {
    }

    /**
     * Test attribute "urls"
     */
    public function testPropertyUrls()
    {
    }
}
