<?php
/**
 * UrlTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Price2Spy API
 *
 * Price2Spy REST API Documentation
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * UrlTypeTest Class Doc Comment
 *
 * @category    Class
 * @description UrlType
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UrlTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UrlType"
     */
    public function testUrlType()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "added_by_id"
     */
    public function testPropertyAddedById()
    {
    }

    /**
     * Test attribute "automatch_url"
     */
    public function testPropertyAutomatchUrl()
    {
    }

    /**
     * Test attribute "counter_failed"
     */
    public function testPropertyCounterFailed()
    {
    }

    /**
     * Test attribute "date_added"
     */
    public function testPropertyDateAdded()
    {
    }

    /**
     * Test attribute "date_modified"
     */
    public function testPropertyDateModified()
    {
    }

    /**
     * Test attribute "last_checked"
     */
    public function testPropertyLastChecked()
    {
    }

    /**
     * Test attribute "last_error"
     */
    public function testPropertyLastError()
    {
    }

    /**
     * Test attribute "last_measurement"
     */
    public function testPropertyLastMeasurement()
    {
    }

    /**
     * Test attribute "modified_by_id"
     */
    public function testPropertyModifiedById()
    {
    }

    /**
     * Test attribute "product_name"
     */
    public function testPropertyProductName()
    {
    }

    /**
     * Test attribute "second_to_last_measurement"
     */
    public function testPropertySecondToLastMeasurement()
    {
    }

    /**
     * Test attribute "show_in_reports"
     */
    public function testPropertyShowInReports()
    {
    }

    /**
     * Test attribute "site_country_iso_code"
     */
    public function testPropertySiteCountryIsoCode()
    {
    }

    /**
     * Test attribute "site_human_name"
     */
    public function testPropertySiteHumanName()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "url_id"
     */
    public function testPropertyUrlId()
    {
    }
}
