<?php
/**
 * RestApiApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Price2Spy API
 *
 * Price2Spy REST API Documentation
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * RestApiApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RestApiApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for approveMatchingSuggestionsUsingPOST
     *
     * approve-matching-suggestions.
     *
     */
    public function testApproveMatchingSuggestionsUsingPOST()
    {
    }

    /**
     * Test case for deleteBrandUsingDELETE
     *
     * deleteBrand.
     *
     */
    public function testDeleteBrandUsingDELETE()
    {
    }

    /**
     * Test case for deleteCategoryUsingDELETE
     *
     * deleteCategory.
     *
     */
    public function testDeleteCategoryUsingDELETE()
    {
    }

    /**
     * Test case for deleteMetadata1UsingDELETE
     *
     * deleteMetadata1.
     *
     */
    public function testDeleteMetadata1UsingDELETE()
    {
    }

    /**
     * Test case for deleteMetadata2UsingDELETE
     *
     * deleteMetadata2.
     *
     */
    public function testDeleteMetadata2UsingDELETE()
    {
    }

    /**
     * Test case for deleteMetadata3UsingDELETE
     *
     * deleteMetadata3.
     *
     */
    public function testDeleteMetadata3UsingDELETE()
    {
    }

    /**
     * Test case for deleteProductUsingDELETE
     *
     * deleteProduct.
     *
     */
    public function testDeleteProductUsingDELETE()
    {
    }

    /**
     * Test case for deleteSuppliersUsingDELETE
     *
     * deleteSupplier.
     *
     */
    public function testDeleteSuppliersUsingDELETE()
    {
    }

    /**
     * Test case for deleteUrlUsingDELETE
     *
     * deleteUrl.
     *
     */
    public function testDeleteUrlUsingDELETE()
    {
    }

    /**
     * Test case for demoteAutomatchUrlUsingGET
     *
     * demoteAutomatchUrl.
     *
     */
    public function testDemoteAutomatchUrlUsingGET()
    {
    }

    /**
     * Test case for getAutomatchUrlsUsingPOST
     *
     * getAutomatchUrls.
     *
     */
    public function testGetAutomatchUrlsUsingPOST()
    {
    }

    /**
     * Test case for getBrandsUsingGET
     *
     * getBrands.
     *
     */
    public function testGetBrandsUsingGET()
    {
    }

    /**
     * Test case for getCategoriesUsingGET
     *
     * getCategories.
     *
     */
    public function testGetCategoriesUsingGET()
    {
    }

    /**
     * Test case for getCurrentPricingDataUsingPOST
     *
     * getCurrentPricingData.
     *
     */
    public function testGetCurrentPricingDataUsingPOST()
    {
    }

    /**
     * Test case for getMatchingSuggestionsUsingPOST
     *
     * get-matching-suggestions.
     *
     */
    public function testGetMatchingSuggestionsUsingPOST()
    {
    }

    /**
     * Test case for getMeasurementsUsingPOST
     *
     * getMeasurements.
     *
     */
    public function testGetMeasurementsUsingPOST()
    {
    }

    /**
     * Test case for getMetadata1UsingGET
     *
     * getMetadata1.
     *
     */
    public function testGetMetadata1UsingGET()
    {
    }

    /**
     * Test case for getMetadata2UsingGET
     *
     * getMetadata2.
     *
     */
    public function testGetMetadata2UsingGET()
    {
    }

    /**
     * Test case for getMetadata3UsingGET
     *
     * getMetadata3.
     *
     */
    public function testGetMetadata3UsingGET()
    {
    }

    /**
     * Test case for getPriceBucketsUsingGET
     *
     * getPriceBuckets.
     *
     */
    public function testGetPriceBucketsUsingGET()
    {
    }

    /**
     * Test case for getProductsUsingPOST
     *
     * getProducts.
     *
     */
    public function testGetProductsUsingPOST()
    {
    }

    /**
     * Test case for getSuppliersUsingGET
     *
     * getSuppliers.
     *
     */
    public function testGetSuppliersUsingGET()
    {
    }

    /**
     * Test case for getUrlsUsingPOST
     *
     * getUrls.
     *
     */
    public function testGetUrlsUsingPOST()
    {
    }

    /**
     * Test case for insertBrandUsingPOST
     *
     * insertBrand.
     *
     */
    public function testInsertBrandUsingPOST()
    {
    }

    /**
     * Test case for insertCategoryUsingPOST
     *
     * insertCategory.
     *
     */
    public function testInsertCategoryUsingPOST()
    {
    }

    /**
     * Test case for insertMetadata1UsingPOST
     *
     * insertMetadata1.
     *
     */
    public function testInsertMetadata1UsingPOST()
    {
    }

    /**
     * Test case for insertMetadata2UsingPOST
     *
     * insertMetadata2.
     *
     */
    public function testInsertMetadata2UsingPOST()
    {
    }

    /**
     * Test case for insertMetadata3UsingPOST
     *
     * insertMetadata3.
     *
     */
    public function testInsertMetadata3UsingPOST()
    {
    }

    /**
     * Test case for insertProductUsingPOST
     *
     * insertProduct.
     *
     */
    public function testInsertProductUsingPOST()
    {
    }

    /**
     * Test case for insertSupplierUsingPOST
     *
     * insertSupplier.
     *
     */
    public function testInsertSupplierUsingPOST()
    {
    }

    /**
     * Test case for insertUrlUsingPOST
     *
     * insertUrl.
     *
     */
    public function testInsertUrlUsingPOST()
    {
    }

    /**
     * Test case for promoteAutomatchUrlUsingGET
     *
     * promoteAutomatchUrl.
     *
     */
    public function testPromoteAutomatchUrlUsingGET()
    {
    }

    /**
     * Test case for rejectAutomatchUrlUsingGET
     *
     * rejectAutomatchUrl.
     *
     */
    public function testRejectAutomatchUrlUsingGET()
    {
    }

    /**
     * Test case for rejectMatchingSuggestionsUsingDELETE
     *
     * reject-matching-suggestions.
     *
     */
    public function testRejectMatchingSuggestionsUsingDELETE()
    {
    }

    /**
     * Test case for updateBrandUsingPUT
     *
     * updateBrand.
     *
     */
    public function testUpdateBrandUsingPUT()
    {
    }

    /**
     * Test case for updateCategoryUsingPUT
     *
     * updateCategory.
     *
     */
    public function testUpdateCategoryUsingPUT()
    {
    }

    /**
     * Test case for updateMetadata1UsingPUT
     *
     * updateMetadata1.
     *
     */
    public function testUpdateMetadata1UsingPUT()
    {
    }

    /**
     * Test case for updateMetadata2UsingPUT
     *
     * updateMetadata2.
     *
     */
    public function testUpdateMetadata2UsingPUT()
    {
    }

    /**
     * Test case for updateMetadata3UsingPUT
     *
     * updateMetadata3.
     *
     */
    public function testUpdateMetadata3UsingPUT()
    {
    }

    /**
     * Test case for updateProductUsingPOST
     *
     * updateProduct.
     *
     */
    public function testUpdateProductUsingPOST()
    {
    }

    /**
     * Test case for updateSupplierUsingPUT
     *
     * updateSupplier.
     *
     */
    public function testUpdateSupplierUsingPUT()
    {
    }

    /**
     * Test case for updateUrlUsingPOST
     *
     * updateUrl.
     *
     */
    public function testUpdateUrlUsingPOST()
    {
    }
}
